# Generated by Django 5.0.6 on 2026-03-16 23:21

import properties.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_larg_alter_property_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(upload_to='images/properties/', validators=[properties.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='images/properties/', validators=[properties.validators.validate_image_file]),
        ),
    ]
