# Generated by Django 4.2 on 2025-06-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='annonce_type',
            field=models.CharField(choices=[('To_sell', 'À vendre'), ('For_rent', 'À louer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/property/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'Maison'), ('Appartment', 'Appartement'), ('Studio', 'studio'), ('Villa', 'Villa'), ('Land', 'Terrain'), ('Commercial', 'Local commercial')], max_length=20),
        ),
    ]
