# Generated by Django 4.2 on 2025-07-02 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_annonce_type_alter_property_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/properties/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='images/properties/'),
        ),
    ]
