# Generated by Django 4.2 on 2025-07-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_propertyimage_is_main_alter_property_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image',
            new_name='main_image',
        ),
    ]
