# Generated by Django 5.0.6 on 2026-03-16 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('properties', '0003_alter_property_main_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='properties.property'),
        ),
    ]
